name: espressocash_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  jupiter_aggregator:
    git:
      url: https://github.com/espresso-cash/espresso-cash-public.git
      path: packages/jupiter_aggregator
  retrofit: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  mews_pedantic: ^0.35.0
  retrofit_generator: ^9.1.7
